### ISSUE TITLE
关于自动装配问题

### ISSUE THREAD

**Issue by livk-cloud** [pagehelper/pagehelper-spring-boot#148]
SpringBoot3-M5删除了spring.factories的自动装配[spring boot wiki](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes)
可以升级一下[自动装配](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes)的方式嘛

**Comment by abel533** [comment]
## 2.6
Changes to Auto-configuration
Auto-configuration Registration
If you have created your own auto-configurations, you should move the registration from spring.factories under the org.springframework.boot.autoconfigure.EnableAutoConfiguration key to a new file named META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports. Rather than a single comma-separate list, each line contains the fully qualified name of an auto-configuration class. See [the included auto-configurations](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports) for an example.

For backwards compatibility, entries in spring.factories will still be honored.

## 3.0

Auto-configuration Registration
Spring Boot 2.7 [introduced](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration) a new META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports file for registering auto-configurations, while maintaining backwards compatibility with registration in spring.factories. With this release, support for registering auto-configurations in spring.factories has been removed in favor of the imports file.

## example

https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

**Comment by abel533** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.developing-auto-configuration
